Traceback (most recent call last):
  File "/home/dallepez/algobio1718/src/main.py", line 55, in <module>
    main()
  File "/home/dallepez/algobio1718/src/main.py", line 34, in main
    BDDE_obj = BDDE(G, patients, k, parameters)
  File "/home/dallepez/algobio1718/src/lib/core.py", line 26, in __init__
    self.pre(self)
  File "/home/dallepez/algobio1718/src/lib/bounds.py", line 53, in pre_bound_means_iterations
    best_vectors[index]=generate_best_vectors(self, self.G)
  File "/home/dallepez/algobio1718/src/lib/bounds.py", line 94, in generate_best_vectors
    if min_prod>best_vectors[u][1]:
IndexError: list index out of range

real	0m13.026s
user	0m12.283s
sys	0m0.471s
